# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/xamarin"

# Exclude files which should not be in the output 
exclude: [README.md,Gemfile,Gemfile.lock]
navigation:
## List your directory names and order here, like this:
## Root Level
    licensing:
        title: "Licensing"
        position: 4
    installation-and-deployment:
        title: "Installation and Deployment"
        position: 5
    controls:
        title: "<b>Xamarin Forms Controls</b>"
        position: 6
    nativecontrols:
        title: "Native Controls Wrappers"
        position: 7
    troubleshooting:
        title: "Troubleshooting"
        position: 11
    styling-and-appearance:
        title: "Styling and Appearance"
        position: 9
    cloud-integration:
        title: "Cloud Integration"
        position: 10
## End Root Level
## Cloud Integration Sub-Folders
    cloud-integration/azure:
        title: "Azure"
        position: 1
    cloud-integration/azure/connect-to-data-in-the-cloud:
        title: "Connect to Data in the Cloud"
        position: 3				
    cloud-integration/azure/cognitive-services:
        title: "Cognitive Services"
        position: 5
    cloud-integration/amazon-web-services:
        title: "Amazon Web Services"
        position: 2
    cloud-integration/amazon-web-services/connect-to-data-in-the-cloud:
        title: "Connect to Data in the Cloud"
        position: 5
## Cloud Integration Sub-Folders
## Styling Sub-Folders
    styling-and-appearance/xamarin-forms-theming:
        title: "Xamarin Forms Theming"
        position: 1
## End Styling Sub-Folders
## Intallation Sub-Folders
    installation-and-deployment/windows:
        title: "Windows"
        position: 3
    installation-and-deployment/mac:
        title: "Mac"
        position: 4
## End Intallation Sub-Folders
## Native Controls Sub-Folders
    nativecontrols/android:
        title: "Android"
        position: 1
    nativecontrols/ios:
        title: "iOS"
        position: 2
    nativecontrols/android/android-native-controls:
        title: "Android Native Controls"
    nativecontrols/ios/ios-native-controls:
        title: "iOS Native Controls"
## End Native Controls Sub-Folders

## Android Controls
    nativecontrols/android/autocomplete:
        title: AutoComplete
        position: 2
    nativecontrols/android/calendar:
        title: Calendar
        position: 3
    nativecontrols/android/chart:
        title: Chart
        position: 4
    nativecontrols/android/dataform:
        title: DataForm
        position: 5
    nativecontrols/android/datasource:
        title: DataSource
        position: 6    
    nativecontrols/android/agauges:
        title: Gauges
        position: 8
    nativecontrols/android/listview:
        title: ListView
        position: 9
    nativecontrols/android/numberpicker:
        title: NumberPicker
        position: 10
    nativecontrols/android/spreadstreamprocessing:
        title: SpreadStreamProcessing
        position: 11
    nativecontrols/android/tabview:
        title: TabView
        position: 12
    nativecontrols/android/ziplibrary:
        title: ZipLibrary
        position: 13
    nativecontrols/android/scrollview:
        title: ScrollView
        position: 14
    nativecontrols/android/sidedrawer:
        title: SideDrawer
        position: 15
    nativecontrols/android/gauges:
        title: Gauges
        position: 16
## End Android Controls

## Android Controls SubFolders
    nativecontrols/android/chart/axes:
        title: Axes
    nativecontrols/android/chart/behaviors:
        title: Behaviors
    nativecontrols/android/chart/series:
        title: Series
    nativecontrols/android/chart/types:
        title: Types
    nativecontrols/android/listview/behaviors:
        title: Behaviors
## End Android Controls SubFolders

## IOS Controls
    nativecontrols/ios/alert:
        title: Alert
        position: 1   
    nativecontrols/ios/autocompletetextview:
        title: AutoCompleteTextView
        position: 3
    nativecontrols/ios/calendar:
        title: Calendar
        position: 4
    nativecontrols/ios/chart:
        title: Chart
        position: 5
    nativecontrols/ios/dataform:
        title: DataForm
        position: 6
    nativecontrols/ios/datasource:
        title: DataSource
        position: 7
    nativecontrols/ios/gauges:
        title: Gauges
        position: 8
    nativecontrols/ios/listview:
        title: ListView
        position: 9
    nativecontrols/ios/sidedrawer:
        title: SideDrawer
        position: 10
    nativecontrols/ios/spreadstreamprocessing:
        title: SpreadStreamProcessing
        position: 11
    nativecontrols/ios/ziplibrary:
        title: ZipLibrary
        position: 13
## End IOS Controls

## iOS Controls SubFolders

    nativecontrols/ios/chart/animations:
        title: Animations
    nativecontrols/ios/chart/axes:
        title: Axes
    nativecontrols/ios/chart/pointlabels:
        title: PointLabels
    nativecontrols/ios/chart/series:
        title: Series
## End iOS Controls SubFolders

## Controls Sub-Folders
    ## DataGrid
    controls/datagrid:
        title: "DataGrid"
    controls/datagrid/columns: 
        title: "Columns"
        position: 2
    controls/datagrid/columns/column-types: 
        title: "Column Types"
        position: 1    
    controls/datagrid/commands:
        title: "Commands"
        position: 9
    controls/datagrid/theming-and-styles: 
        title: "Theming and Styles"
        position: 10
    controls/datagrid/howto: 
        title: "How To"
        position: 11
    ## End DataGrid
    
    ## Entry
    controls/entry:
        title: "Entry"
    ## End Entry
    
     ## Expander
    controls/expander:
        title: "Expander"
    ## End Expander
    
    ## NumericInput
    controls/numericinput:
        title: "NumericInput"
    ## End NumericInput
    
    ## Path
    controls/path:
        title: "Path"
    controls/path/getting-started:
        title: "Getting Started"
    ## End Path
    
    ## Accordion
    controls/accordion:
        title: "Accordion"
    ##End Accordion
    
    ## AutoComplete
    controls/autocomplete:
        title: "AutoComplete"
        ## AutoComplete Sub-Folders
    controls/autocomplete/getting-started:
        title: "Getting Started"
        position: 1
    controls/autocomplete/features:
        title: "Features"
        position: 2
        ## End AutoComplete Sub-Folders
    ## End AutoComplete
    
    ## AutoCompleteView
    controls/autocompleteview:
        title: "AutoCompleteView(beta)"
    ## End AutoCompleteView
    
    ## Barcode
    controls/barcode:
        title: "Barcode"
        ## Barcode Sub-Folders
    controls/barcode/getting-started:
        title: "Getting Started"
        position: 1
    controls/barcode/features:
        title: "Features"
        position: 2
    controls/barcode/supported-types:
        title: "Supported Types"
        position: 3
            ## Barcode Supported Types Sub-Folders
    controls/barcode/supported-types/1d-barcodes:
        title: "1D Barcodes"
        position: 2
    controls/barcode/supported-types/2d-barcodes:
        title: "2D Barcodes"
        position: 1
           ## End Barcode Supported Types Sub-Folders
        ## End Barcode Sub-Folders
    ## End Barcode
    ## Border
    controls/border:
        title: "Border"
    ## End Border
    ## BusyIndicator
    controls/busyindicator:
        title: "BusyIndicator"
        ## BusyIndicator Sub-Folders
    controls/busyindicator/getting-started:
        title: "Getting Started"
        position: 1
    controls/busyindicator/features:
        title: "Features"
        position: 2
        ## End BusyIndicator Sub-Folders
    ## End BusyIndicator
    ## Button
    controls/button:
        title: "Button"
        ## Button Sub-Folders
    controls/button/getting-started:
        title: "Getting Started"
        position: 1
    controls/button/features:
        title: "Features"
        position: 2
    controls/button/howto:
        title: "How To"
        position: 3
        ## End Button Sub-Folders
    ## End Button
    ## Calendar
    controls/calendar:
        title: "Calendar &amp; Scheduling"
        ## Calendar Sub-Folders
    controls/calendar/styling:
        title: "Styling"
        position: 8
    controls/calendar/styling/custom-renderers:
        title: "Custom Renderers"
    controls/calendar/how-to:
        title: "How To"
        position: 9
        ## End Calendar Sub-Folders
    ## End Calendar
    ## Chart
    controls/chart:
        title: "Chart"
        ## Chart Sub-Folders
    controls/chart/types:
        title: "Chart Types"
        position: 3
    controls/chart/axes:
        title: "Axes"
        position: 4
    controls/chart/behaviors:
        title: "Behaviors"
        position: 6
    controls/chart/series:
        title: "Series"
        position: 5
            ## Chart Series Sub-Folders
    controls/chart/series/cartesian:
        title: "CartesianSeries"
        position: 1
                ## Chart Series CartesianSeries Sub-Folders
    controls/chart/series/cartesian/features:
        title: "Features"
        position: 1
                ## End Chart Series CartesianSeries Sub-Folders
    controls/chart/series/pie:
        title: "PieSeries"
        position: 2
    controls/chart/series/financial:
        title: "Financial Series"
        position: 3
            ## End Chart Series Sub-Folders
    controls/chart/how-to:
        title: "How To"
        position: 11
        ## End Chart Sub-Folders
    ## End Chart
    ## CheckBox
    controls/checkbox:
        title: "CheckBox"
    ## End CheckBox
    ## Chat
    controls/chat:
        title: "Conversational UI"
        ## Chat Sub-Folders  
    controls/chat/chat-items:
        title: "Chat Items"
        position: 3
    controls/chat/chat-picker:
        title: "ChatPicker"
        position: 4
                ## ChatPicker Sub-Folders
    controls/chat/chat-picker/cards:
        title: "CardPicker"
        position: 5
                ## End ChatPicker Sub-Folders  
    ## End Chat
    ## DataForm
    controls/dataform:
        title: "DataForm"
        ## DataForm Sub-Folders
    controls/dataform/getting-started:
        title: "Getting Started"
        position: 1
    controls/dataform/annotations:
        title: "Data Annotations"
        position: 4
    controls/dataform/styling:
       title: "Styling"
       position: 9    
    controls/dataform/howto:
        title: "How To"
        position: 10
        ## End DataForm Sub-Folders
    ## End DataForm
    ## Gauge
    controls/gauge:
        title: "Gauge"
        ## Gauge Sub-Folders
    controls/gauge/getting-started:
        title: "Getting Started"
        position: 1
    controls/gauge/gauge-types:
        title: "Gauge Types"
        position: 2
    controls/gauge/features:
        title: "Features"
        position: 3
        ## End Gauge Sub-Folders
    ## End Gauge
    ## ListView
    controls/listview:
        title: "ListView"
        ## ListView Sub-Folders
    controls/listview/grouping:
        title: "Grouping"
        position: 4
    controls/listview/gestures:
        title: "Gestures"
        position: 10
    controls/listview/features:
        title: "Features"
        position: 3
    controls/listview/cells:
        title: Cells
        position: 2   
    controls/listview/styling:
            title: "Theming and Styles"
            position: 13          
    controls/listview/howto:
        title: "How To"
        position: 15
        ## End ListView Sub-Folders
    ## End ListView
    ## SideDrawer
    controls/sidedrawer:
        title: "SideDrawer"
        ## SideDrawer Sub-Folders
    controls/sidedrawer/getting-started:
        title: "Getting Started"
        position: 1    
    controls/sidedrawer/features:
        title: "Features"
        position: 5
        ## End SideDrawer Sub-Folders
    ## End SideDrawer
    ## Rating
    controls/rating:
        title: "Rating"
        ## SideDrawer Sub-Folders
    controls/rating/getting-started:
        title: "Getting Started"
        position: 1
    controls/rating/features:
        title: "Features"
        position: 2
        ## End SideDrawer Sub-Folders
    ## End Rating
    ## SegmentedControl
    controls/segmentedcontrol:
        title: "SegmentedControl"
        ## SegmentedControl Sub-Folders
    controls/segmentedcontrol/getting-started:
        title: "Getting Started"
        position: 1
    controls/segmentedcontrol/features:
        title: "Features"
        position: 2
        ## End SegmentedControl Sub-Folders
    ## End SegmentedControl
    ## TabView
    controls/tabview:
        title: "TabView"
        ## TabView Sub-Folders
    controls/tabview/getting-started:
        title: "Getting Started"
        position: 1
    controls/tabview/features:
        title: "Features"
        position: 2
        ## End TabView Sub-Folders
    ## End TabView
   ## TreeView
    controls/treeview:
        title: "TreeView"
    controls/treeview/getting-started:
        title: "Getting Started"
        position: 3
    controls/treeview/features:
        title: "Features"
        position: 4
    ## End TreeView
    ## ZipLibrary
    controls/ziplibrary:
        title: "ZipLibrary"
    ## End ZipLibrary
    ## SpreadStreamProcessing
    controls/spreadstreamprocessing:
        title: "SpreadStreamProcessing"
    ## End SpreadStreamProcessing
    ## MaskedInput
    controls/maskedinput:
        title: "MaskedInput"
    controls/maskedinput/getting-started:
        title: "Getting Started"
        position: 1
    controls/maskedinput/features:
        title: "Features"
        position: 2
    ## End MaskedInput
    ## SlideView
    controls/slideview:
        title: "SlideView"    
    ## End SlideView
## End Controls Sub-Folders

## The application virtual path
baseurl: "/devtools/xamarin"


## The Kendo UI version used
cdnVersion: "2016.2.607"

## The MVC Core version used
mvcCoreVersion: "2016.2.616"

## The product name
productName: "Telerik UI for Xamarin"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
        product: "xamarin-ui"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Feedback Form Google Sheet ID
ff-sheet-id: 1XHRCSFFh2aL9W_EfhfO2lXDGTR8kKFnK8x289HbujIU

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:hqd69dmjy2k'



# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
