# The public documentation URL, used for sitemap.xml
url: "http://docs.telerik.com/devtools/xamarin"

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock]
navigation:
## List your directory names and order here, like this:
## Root Level
    installation-and-deployment:
        title: "Installation and Deployment"
        position: 3
    controls:
        title: "Controls"
        position: 4
    troubleshooting:
        title: "Troubleshooting"
        position: 5
## End Root Level
## Intallation Sub-Folders
    installation-and-deployment/windows:
        title: "Windows"
        position: 2
    installation-and-deployment/mac:
        title: "Mac"
        position: 3
## End Intallation Sub-Folders
## Controls Sub-Folders
    ## AutoComplete
    controls/autocomplete:
        title: "Autocomplete"
        ## AutoComplete Sub-Folders
    controls/autocomplete/getting-started:
        title: "Getting Started"
        position: 1
    controls/autocomplete/features:
        title: "Features"
        position: 2
        ## End AutoComplete Sub-Folders
    ## End AutoComplete
    ## BusyIndicator
    controls/busyindicator:
        title: "BusyIndicator"
        ## BusyIndicator Sub-Folders
    controls/busyindicator/getting-started:
        title: "Getting Started"
        position: 1
    controls/busyindicator/features:
        title: "Features"
        position: 2
        ## End BusyIndicator Sub-Folders
    ## End BusyIndicator
    ## Calendar
    controls/calendar:
        title: "Calendar"
        ## Calendar Sub-Folders
    controls/calendar/getting-started:
        title: "Getting Started"
        position: 2
    controls/calendar/features:
        title: "Features"
        position: 5
    controls/calendar/styling:
        title: "Styling"
        position: 6
    controls/calendar/styling/custom-renderers:
        title: "Custom Renderers"
    controls/calendar/how-to:
        title: "How To"
        position: 7
        ## End Calendar Sub-Folders
    ## End Calendar
    ## Chart
    controls/chart:
        title: "Chart"
        ## Chart Sub-Folders
    controls/chart/getting-started:
        title: "Getting Started"
        position: 2
    controls/chart/axes:
        title: "Axes"
        position: 4
    controls/chart/behaviors:
        title: "Behaviors"
        position: 6
    controls/chart/series:
        title: "Series"
        position: 5
            ## Chart Series Sub-Folders
    controls/chart/series/cartesian:
        title: "CartesianSeries"
        position: 1
                ## Chart Series CartesianSeries Sub-Folders
    controls/chart/series/cartesian/features:
        title: "Features"
        position: 1
                ## End Chart Series CartesianSeries Sub-Folders
    controls/chart/series/pie:
        title: "PieSeries"
        position: 2
            ## End Chart Series Sub-Folders
    controls/chart/types:
        title: "Chart Types"
        position: 3
    controls/chart/how-to:
        title: "How To"
        position: 9
        ## End Chart Sub-Folders
    ## End Chart
    ## DataForm
    controls/dataform:
        title: "DataForm"
        ## DataForm Sub-Folders
    controls/dataform/getting-started:
        title: "Getting Started"
        position: 1
    controls/dataform/annotations:
        title: "Data Annotations"
        position: 4
    controls/dataform/styling:
       title: "Styling"
       position: 9    
    controls/dataform/howto:
        title: "How To"
        position: 10
        ## End DataForm Sub-Folders
    ## End DataForm
    ## Gauge
    controls/gauge:
        title: "Gauge"
        ## Gauge Sub-Folders
    controls/gauge/getting-started:
        title: "Getting Started"
        position: 1
    controls/gauge/gauge-types:
        title: "Gauge Types"
        position: 2
    controls/gauge/features:
        title: "Features"
        position: 3
        ## End Gauge Sub-Folders
    ## End Gauge
    ## ListView
    controls/listview:
        title: "ListView"
        ## ListView Sub-Folders
    controls/listview/getting-started:
        title: "Getting Started"
        position: 1
    controls/listview/gestures:
        title: "Gestures"
        position: 4
    controls/listview/features:
        title: "Features"
        position: 4
        ## End ListView Sub-Folders
    ## End ListView
    ## SideDrawer
    controls/sidedrawer:
        title: "SideDrawer"
        ## SideDrawer Sub-Folders
    controls/sidedrawer/getting-started:
        title: "Getting Started"
        position: 1    
    controls/sidedrawer/features:
        title: "Features"
        position: 5
        ## End SideDrawer Sub-Folders
    ## End SideDrawer
    ## Rating
    controls/rating:
        title: "Rating"
        ## SideDrawer Sub-Folders
    controls/rating/getting-started:
        title: "Getting Started"
        position: 1
        ## End SideDrawer Sub-Folders
    ## End Rating
    ## SegmentControl
    controls/segmentcontrol:
        title: "SegmentControl"
        ## SegmentControl Sub-Folders
    controls/segmentcontrol/getting-started:
        title: "Getting Started"
        position: 1
    controls/segmentcontrol/features:
        title: "Features"
        position: 2
        ## End SegmentControl Sub-Folders
    ## End SegmentControl
    ## ZipLibrary
    controls/ziplibrary:
        title: "ZipLibrary"
    ## End ZipLibrary
    ## SpreadStreamProcessing
    controls/spreadstreamprocessing:
        title: "SpreadStreamProcessing"
    ## End SpreadStreamProcessing
## End Controls Sub-Folders

## The application virtual path
baseurl: "/devtools/xamarin"


## The Kendo UI version used
cdnVersion: "2016.2.607"

## The MVC Core version used
mvcCoreVersion: "2016.2.616"

## The product name
productName: "Telerik UI for Xamarin Forms"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
        product: "xamarin-ui"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Feedback Form Google Sheet ID
ff-sheet-id: 1XHRCSFFh2aL9W_EfhfO2lXDGTR8kKFnK8x289HbujIU

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:hqd69dmjy2k'



# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
