# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/xamarin"

# Exclude files which should not be in the output 
exclude: [README.md,Gemfile,Gemfile.lock]
exclude_navigation: [knowledge-base/*]

navigation:
## List your directory names and order here, like this:
## Root Level
    "knowledge-base":
        title: "Knowledge Base"
        position: 13
    licensing:
        title: "Licensing"
        position: 4
    installation-and-deployment:
        title: "Installation and Deployment"
        position: 5
    upgrade:
        title: "Upgrade"
        position: 6
    controls:
        title: "<b>Xamarin Forms Controls</b>"
        position: 7
    nativecontrols:
        title: "Native Controls Wrappers"
        position: 8
    troubleshooting:
        title: "Troubleshooting"
        position: 12
    styling-and-appearance:
        title: "Styling and Appearance"
        position: 10
    cloud-integration:
        title: "Cloud Integration"
        position: 11
    "api-reference":
        title: "Api Reference"
        position: 23
## End Root Level
## Cloud Integration Sub-Folders
    cloud-integration/azure:
        title: "Azure"
        position: 1
    cloud-integration/azure/connect-to-data-in-the-cloud:
        title: "Connect to Data in the Cloud"
        position: 3				
    cloud-integration/azure/cognitive-services:
        title: "Cognitive Services"
        position: 5
    cloud-integration/amazon-web-services:
        title: "Amazon Web Services"
        position: 2
    cloud-integration/amazon-web-services/connect-to-data-in-the-cloud:
        title: "Connect to Data in the Cloud"
        position: 5
## Cloud Integration Sub-Folders
## Styling Sub-Folders
    styling-and-appearance/xamarin-forms-theming:
        title: "Xamarin Forms Theming"
        position: 1
## End Styling Sub-Folders
## Intallation Sub-Folders
    installation-and-deployment/windows:
        title: "Windows"
        position: 3
    installation-and-deployment/mac:
        title: "Mac"
        position: 4
## End Intallation Sub-Folders
## Native Controls Sub-Folders
    nativecontrols/android:
        title: "Android"
        position: 1
    nativecontrols/ios:
        title: "iOS"
        position: 2
    nativecontrols/android/android-native-controls:
        title: "Android Native Controls"
    nativecontrols/ios/ios-native-controls:
        title: "iOS Native Controls"
## End Native Controls Sub-Folders

## Android Controls
    nativecontrols/android/autocomplete:
        title: AutoComplete
        position: 2
    nativecontrols/android/calendar:
        title: Calendar
        position: 3
    nativecontrols/android/chart:
        title: Chart
        position: 4
    nativecontrols/android/dataform:
        title: DataForm
        position: 5
    nativecontrols/android/datasource:
        title: DataSource
        position: 6    
    nativecontrols/android/agauges:
        title: Gauges
        position: 8
    nativecontrols/android/listview:
        title: ListView
        position: 9
    nativecontrols/android/numberpicker:
        title: NumberPicker
        position: 10
    nativecontrols/android/spreadstreamprocessing:
        title: SpreadStreamProcessing
        position: 11
    nativecontrols/android/tabview:
        title: TabView
        position: 12
    nativecontrols/android/ziplibrary:
        title: ZipLibrary
        position: 13
    nativecontrols/android/scrollview:
        title: ScrollView
        position: 14
    nativecontrols/android/sidedrawer:
        title: SideDrawer
        position: 15
    nativecontrols/android/gauges:
        title: Gauges
        position: 16
## End Android Controls

## Android Controls SubFolders
    nativecontrols/android/chart/axes:
        title: Axes
    nativecontrols/android/chart/behaviors:
        title: Behaviors
    nativecontrols/android/chart/series:
        title: Series
    nativecontrols/android/chart/types:
        title: Types
    nativecontrols/android/listview/behaviors:
        title: Behaviors
## End Android Controls SubFolders

## IOS Controls
    nativecontrols/ios/alert:
        title: Alert
        position: 1   
    nativecontrols/ios/autocompletetextview:
        title: AutoCompleteTextView
        position: 3
    nativecontrols/ios/calendar:
        title: Calendar
        position: 4
    nativecontrols/ios/chart:
        title: Chart
        position: 5
    nativecontrols/ios/dataform:
        title: DataForm
        position: 6
    nativecontrols/ios/datasource:
        title: DataSource
        position: 7
    nativecontrols/ios/gauges:
        title: Gauges
        position: 8
    nativecontrols/ios/listview:
        title: ListView
        position: 9
    nativecontrols/ios/sidedrawer:
        title: SideDrawer
        position: 10
    nativecontrols/ios/spreadstreamprocessing:
        title: SpreadStreamProcessing
        position: 11
    nativecontrols/ios/ziplibrary:
        title: ZipLibrary
        position: 13
## End IOS Controls

## iOS Controls SubFolders

    nativecontrols/ios/chart/animations:
        title: Animations
    nativecontrols/ios/chart/axes:
        title: Axes
    nativecontrols/ios/chart/pointlabels:
        title: PointLabels
    nativecontrols/ios/chart/series:
        title: Series
## End iOS Controls SubFolders

## Controls Sub-Folders
    ## DataGrid
    controls/datagrid:
        title: "DataGrid"
    controls/datagrid/columns: 
        title: "Columns"
        position: 2
    controls/datagrid/columns/column-types: 
        title: "Column Types"
        position: 1    
    controls/datagrid/commands:
        title: "Commands"
        position: 9
    controls/datagrid/theming-and-styles: 
        title: "Theming and Styles"
        position: 10
    controls/datagrid/howto: 
        title: "How To"
        position: 11
    ## End DataGrid
    
     ## DockLayout
    controls/docklayout:
        title: "DockLayout"
    ## End Entry
    
    ## Entry
    controls/entry:
        title: "Entry"
    ## End Entry
    
     ## Expander
    controls/expander:
        title: "Expander"
    ## End Expander
    
    ## NumericInput
    controls/numericinput:
        title: "NumericInput"
    ## End NumericInput
    
    ## Path
    controls/path:
        title: "Path"   
    ## End Path
    
    ## PdfProcessing
    controls/pdfprocessing:
        title: "PdfProcessing"
    ## End PdfProcessing
    
     ## PdfViewer
    controls/pdfviewer:
        title: "PdfViewer"
    ## End PdfViewer
    
    ## Popup
    controls/popup:
        title: "Popup"
    ## End Popup
    
    ## Accordion
    controls/accordion:
        title: "Accordion"
    ##End Accordion
    
    ## AutoComplete
    controls/autocomplete:
        title: "AutoComplete(obsolete)"
        ## AutoComplete Sub-Folders
    controls/autocomplete/getting-started:
        title: "Getting Started"
        position: 1
    controls/autocomplete/features:
        title: "Features"
        position: 2
        ## End AutoComplete Sub-Folders
    ## End AutoComplete
    
    ## AutoCompleteView
    controls/autocompleteview:
        title: "AutoCompleteView"
    controls/autocompleteview/templates: 
        title: "Custom Templates"
        position: 11
    ## End AutoCompleteView
    
    ## Barcode
    controls/barcode:
        title: "Barcode"
        ## Barcode Sub-Folders  
    controls/barcode/supported-types:
        title: "Supported Types"
        position: 3
            ## Barcode Supported Types Sub-Folders
    controls/barcode/supported-types/1d-barcodes:
        title: "1D Barcodes"
        position: 2
    controls/barcode/supported-types/2d-barcodes:
        title: "2D Barcodes"
        position: 1
           ## End Barcode Supported Types Sub-Folders
        ## End Barcode Sub-Folders
    ## End Barcode
    ## Border
    controls/border:
        title: "Border"
    ## End Border
    ## BusyIndicator
    controls/busyindicator:
        title: "BusyIndicator"
        ## BusyIndicator Sub-Folders
    controls/busyindicator/getting-started:
        title: "Getting Started"
        position: 1
    controls/busyindicator/features:
        title: "Features"
        position: 2
        ## End BusyIndicator Sub-Folders
    ## End BusyIndicator
    ## Button
    controls/button:
        title: "Button"
        ## Button Sub-Folders
    controls/button/getting-started:
        title: "Getting Started"
        position: 1
    controls/button/features:
        title: "Features"
        position: 2
    controls/button/howto:
        title: "How To"
        position: 3
        ## End Button Sub-Folders
    ## End Button
    ## Calendar
    controls/calendar:
        title: "Calendar &amp; Scheduling"
        ## Calendar Sub-Folders
    controls/calendar/view-modes:
        title: "View Modes"
        position: 3
    controls/calendar/recurrence:
        title: "Recurrence"
        position: 6
    controls/calendar/styling:
        title: "Styling"
        position: 11
    controls/calendar/styling/custom-renderers:
        title: "Custom Renderers"
    controls/calendar/how-to:
        title: "How To"
        position: 12
        ## End Calendar Sub-Folders
    ## End Calendar
    ## Chart
    controls/chart:
        title: "Chart"
        ## Chart Sub-Folders
    controls/chart/types:
        title: "Chart Types"
        position: 3
    controls/chart/axes:
        title: "Axes"
        position: 4
    controls/chart/behaviors:
        title: "Behaviors"
        position: 6
    controls/chart/series:
        title: "Series"
        position: 5
            ## Chart Series Sub-Folders
    controls/chart/series/cartesian:
        title: "CartesianSeries"
        position: 2
                ## Chart Series CartesianSeries Sub-Folders
    controls/chart/series/cartesian/features:
        title: "Features"
        position: 1
                ## End Chart Series CartesianSeries Sub-Folders
    controls/chart/series/pie:
        title: "PieSeries"
        position: 3
    controls/chart/series/financial:
        title: "Financial Series"
        position: 4
            ## End Chart Series Sub-Folders
    controls/chart/how-to:
        title: "How To"
        position: 11
        ## End Chart Sub-Folders
    ## End Chart
    ## CheckBox
    controls/checkbox:
        title: "CheckBox"
    ## End CheckBox
    ## Chat
    controls/chat:
        title: "Conversational UI"
        ## Chat Sub-Folders  
    controls/chat/chat-items:
        title: "Chat Items"
        position: 3
    controls/chat/chat-picker:
        title: "ChatPicker"
        position: 4
                ## ChatPicker Sub-Folders
    controls/chat/chat-picker/cards:
        title: "CardPicker"
        position: 5
                ## End ChatPicker Sub-Folders  
    ## End Chat
    ## DataForm
    controls/dataform:
        title: "DataForm"
        ## DataForm Sub-Folders
    controls/dataform/annotations:
        title: "Data Annotations"
        position: 4
    controls/dataform/styling:
       title: "Styling"
       position: 9    
    controls/dataform/howto:
        title: "How To"
        position: 10
        ## End DataForm Sub-Folders
    ## End DataForm
    ## Gauge
    controls/gauge:
        title: "Gauge"
        ## Gauge Sub-Folders
    controls/gauge/gauge-types:
        title: "Gauge Types"
        position: 2
        ## End Gauge Sub-Folders
    ## End Gauge
    ## ImageEditor
    controls/imageeditor:
        title: "ImageEditor"
        ## ImageEditor Sub-Folders
    controls/imageeditor/styling:
        title: "Styling"
        position: 9
        ## End ImageEditor Sub-Folders
    ## End ImageEditor
    ## ListView
    controls/listview:
        title: "ListView"
        ## ListView Sub-Folders
    controls/listview/grouping:
        title: "Grouping"
        position: 4
    controls/listview/gestures:
        title: "Gestures"
        position: 11
    controls/listview/cells:
        title: Cells
        position: 2   
    controls/listview/styling:
        title: "Theming and Styles"
        position: 14         
    controls/listview/howto:
        title: "How To"
        position: 15
        ## End ListView Sub-Folders
    ## End ListView
    ## Map
    controls/map:
        title: "Map"
        ## Map Sub-Folders
    controls/map/layers:
        title: "Layers"
        position: 3
    controls/map/styling:
        title: "Styling"
        position: 9
        ## End Map Sub-Folders
    ## End Map
    ## SideDrawer
    controls/sidedrawer:
        title: "SideDrawer"      
    ## End SideDrawer
    ## Rating
    controls/rating:
        title: "Rating"    
    ## End Rating
    ## SegmentedControl
    controls/segmentedcontrol:
        title: "SegmentedControl"
        ## SegmentedControl Sub-Folders
    controls/segmentedcontrol/getting-started:
        title: "Getting Started"
        position: 1
    controls/segmentedcontrol/features:
        title: "Features"
        position: 2
        ## End SegmentedControl Sub-Folders
    ## End SegmentedControl
    ## TabView
    controls/tabview:
        title: "TabView"
    ## End TabView
   ## TreeView
    controls/treeview:
        title: "TreeView"
    controls/treeview/styling:
        title: "Theming and Styles"
        position: 10
    ## End TreeView
    ## ZipLibrary
    controls/ziplibrary:
        title: "ZipLibrary"
    ## End ZipLibrary
    ## SpreadStreamProcessing
    controls/spreadstreamprocessing:
        title: "SpreadStreamProcessing"
    ## End SpreadStreamProcessing
    ## MaskedInput
    controls/maskedinput:
        title: "MaskedInput"
    ## End MaskedInput
    ## SlideView
    controls/slideview:
        title: "SlideView"    
    ## End SlideView
## End Controls Sub-Folders

## The application virtual path
baseurl: "/devtools/xamarin"

api_reference_url: "api/"

## The MVC Core version used
mvcCoreVersion: "2016.2.616"

## The product name
productName: "Telerik UI for Xamarin"
product: "Telerik UI for Xamarin"
platform: xamarin

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "xamarin-ui"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Feedback Form Google Sheet ID
ff-sheet-id: 1XHRCSFFh2aL9W_EfhfO2lXDGTR8kKFnK8x289HbujIU

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:hqd69dmjy2k'
gcs_api_key: 'AIzaSyBNBA7GFG6zyMuswUt4MB_FSXKVgtTTe7k'

tabbed_code_marker_length: 3
tabbed_code_complex_separator: true

edit_repo_url: https://github.com/telerik/xamarin-forms-docs/edit/master
download: https://www.telerik.com/download/xamarin-ui
nav:
  "Demos": https://www.telerik.com/support/demos#mobile
  "Whats New": https://www.telerik.com/support/whats-new/xamarin-ui
  "About": https://www.telerik.com/xamarin-ui
  "Pricing": https://www.telerik.com/purchase/xamarin-ui

footer:
-
  title: "Sample Applications"
  links:
    "Telerik Tagit": https://www.telerik.com/xamarin-ui/telerik-tagit
    "iOS Demo App": https://itunes.apple.com/dm/app/telerik-ui-for-xamarin-)examples/id1083924868?mt=8
    "Android Demo App": https://play.google.com/store/apps/details?id=com.telerik.xamarin&hl=en
-
  title: "Support Resources"
  links:
    "Xamarin.Forms SDK Examples": https://github.com/telerik/xamarin-forms-sdk
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/xamarin
    "Blogs": https://www.telerik.com/blogs/mobile
    "Feedback Portal": https://feedback.progress.com/project/168
  

footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

has_kb_portal: true
    
# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
